name: empabee
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5 
  http: ^1.2.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  dio: ^5.4.1
  go_router: ^13.2.0
  provider: ^6.1.2
  logger: ^2.1.0
  jwt_decoder: ^2.0.1
  hidden_drawer_menu: ^3.0.1
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.0
dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoSolo.png"
  adaptive_icon-background: "assets/images/logoSolo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
flutter:
  uses-material-design: true
  assets:
    - assets/images/ic_imslogo.png
    - assets/images/googlelogo.png
    - assets/images/fblogo.jpg
    - assets/images/twitterlogo.jpg
    - assets/images/ulogo.png
    - assets/images/ulogo.jpg
    - assets/images/login.png
    - assets/images/logo.png
    - assets/images/powered_by.png
    - assets/images/logoSolo.png
    - assets/images/LogoEmpabee.png
    - assets/images/qrcode-generado.png
    - assets/images/splashEmpa.png
    - assets/images/splashScreen.svg
    - assets/images/loginPortadaLogo.png
    - assets/images/colmena.svg

